import { useState } from "react";
import {
    AlertCircle,
    Brain,
    ChevronDown,
    ChevronRight,
    Cloud,
    DownloadCloud,
    GitFork,
    HardDrive,
    Loader2,
} from "lucide-react";
import ConfigGrid, { FORBIDDEN_KEYS } from "../ui/ConfigGrid";
import EvaluationNode from "./EvaluationNode";
import type { RegistryData, SyncPayload } from "../../types";
import DeleteButton from "../ui/DeleteButton";
import { useQueryClient } from "@tanstack/react-query";
import { syncExperimentLocally } from "../../api";
import SyncWorkspaceButton from "../ui/SyncWorkspaceButton";

interface Props {
    modelHash: string;
    modelObj: any;
    femConfig: any;
    registry: RegistryData;
    serverIsConnected: boolean;
    onFineTune: (
        modelHash: string,
        modelType: string,
        solverConfig: any,
        femConfig: any,
    ) => void;
}

// Intercepts the raw Julia string and converts it into a clean object
const parseSchedulerString = (sched: any) => {
    if (!sched) return null;
    if (typeof sched === "object") return sched; // Already parsed

    const schedStr = String(sched);
    if (schedStr.includes("CosineAnnealing")) {
        const match = schedStr.match(
            /max=([0-9.eE+-]+)_min=([0-9.eE+-]+)_ep=([0-9]+)/i,
        );
        if (match) {
            return {
                type: "Cosine",
                lr_max: match[1],
                lr_min: match[2],
                epochs: match[3],
            };
        }
    } else if (schedStr.includes("ReduceLROnPlateau")) {
        const match = schedStr.match(
            /pat=([0-9]+)_fac=([0-9.eE+-]+)_min=([0-9.eE+-]+)/i,
        );
        if (match) {
            return {
                type: "Plateau",
                patience: match[1],
                factor: match[2],
                min_lr: match[3],
            };
        }
    }
    return schedStr; // Fallback
};

export default function ModelNode({
    modelHash,
    modelObj,
    femConfig,
    registry,
    serverIsConnected,
    onFineTune,
}: Props) {
    const [isExpanded, setIsExpanded] = useState(false);

    // Sync state
    const [isSyncing, setIsSyncing] = useState(false);
    const [syncError, setSyncError] = useState<string | null>(null);
    const queryClient = useQueryClient();

    // Metadata flags
    const isShared = modelObj._isShared;
    const isLocal = modelObj._isLocal;

    // Filter evaluations linking to this model
    const linkedEvals = Object.entries(registry.evaluations).filter(
        ([_, e]) => e.model_hash === modelHash,
    );

    // Safe Parsing for Backward Compatibility
    const solver = modelObj.solver || modelObj;
    const solverType =
        modelObj.solver_type ||
        (modelObj.model_type
            ? `${modelObj.model_type}Solver`
            : "UnknownSolver");

    // Intercept the new and the old key generated by Julia
    const rawScheduler = solver.lr_scheduler || solver.scheduler_info;
    const parsedScheduler = parseSchedulerString(rawScheduler);

    // Remove the old string keys and inject the formatted object
    const sanitizedSolver = { ...solver };
    delete sanitizedSolver.lr_scheduler;
    delete sanitizedSolver.scheduler_info;

    if (parsedScheduler && typeof parsedScheduler === "object") {
        sanitizedSolver.Learning_Rate_Schedule = parsedScheduler;
    }

    const buildCompactModelString = () => {
        const parts: string[] = [];

        // Specific group for DeepONet
        if (solverType.includes("DeepONet") || solverType.includes("NOMAD")) {
            if (solver.p_latent !== undefined && solver.hidden !== undefined) {
                parts.push(`p=${solver.p_latent} • hidden=${solver.hidden}`);
            }
            if (solver.m_sensors !== undefined)
                parts.push(`m=${solver.m_sensors}`);
        }

        // Specific Group for FNO
        if (solverType.includes("FNO")) {
            if (solver.modes !== undefined) {
                // Both array [16] and object {"1": 16} for retro-compatibility
                const m = Array.isArray(solver.modes)
                    ? `[${solver.modes.join(",")}]`
                    : typeof solver.modes === "object"
                      ? `[${Object.values(solver.modes).join(",")}]`
                      : solver.modes;
                parts.push(`modes=${m}`);
            }
            if (solver.hidden_channels !== undefined) {
                const hc = Array.isArray(solver.hidden_channels)
                    ? `[${solver.hidden_channels.join(",")}]`
                    : typeof solver.hidden_channels === "object"
                      ? `[${Object.values(solver.hidden_channels).join(",")}]`
                      : solver.hidden_channels;
                parts.push(`channels=${hc}`);
            }
        }

        // Shared parameters
        const epochs = solver.epochs || solver.n_epochs;
        if (epochs !== undefined) parts.push(`epochs=${epochs}`);

        // Clean Scheduler Injection
        if (parsedScheduler && typeof parsedScheduler === "object") {
            if (parsedScheduler.type === "Cosine") {
                parts.push(
                    `LR: Cosine [${parsedScheduler.lr_max} ↘ ${parsedScheduler.lr_min}]`,
                );
            } else if (parsedScheduler.type === "Plateau") {
                parts.push(`LR: Plateau (pat=${parsedScheduler.patience})`);
            }
        }

        const groupedKeys = [
            "p_latent",
            "hidden",
            "m_sensors",
            "modes",
            "hidden_channels",
            "epochs",
            "n_epochs",
            "lr_scheduler",
            "scheduler_info",
        ];

        Object.entries(solver).forEach(([k, v]) => {
            if (!FORBIDDEN_KEYS.includes(k) && !groupedKeys.includes(k)) {
                if (typeof v !== "object" || v === null) {
                    parts.push(`${k}=${v}`);
                }
            }
        });

        return parts.join(" | ");
    };

    const compactConfigString = buildCompactModelString();

    // Extract data info for the payload
    const dataHash = modelObj.data_hash;
    const dataObj = registry.data[dataHash] || {};

    // Build the shared partial SyncPayload
    const syncPayload: SyncPayload = {
        model_type: solverType,
        hashes: {
            data_hash: dataHash,
            model_hash: modelHash,
        },
        fem_config: femConfig,
        solver_config: solver,
        data_url: dataObj.data_url ?? undefined,
        model_url: modelObj.model_url ?? undefined,
    };

    // Unified handler for the Fine-Tune / Sync action
    const handleFineTuneAction = async () => {
        if (isLocal) {
            // Fast-path: already on disk, trigger directly
            onFineTune(modelHash, solverType, solver, femConfig);
            return;
        }

        // Needs to be pulled from remote first
        setIsSyncing(true);
        setSyncError(null);
        try {
            // Call the sync API with the shared payload
            const res = await syncExperimentLocally(syncPayload);

            if (res.status === "success") {
                // Invalidate query to update UI badges (Cloud -> Cloud + Local)
                queryClient.invalidateQueries({
                    queryKey: ["registry", "merged"],
                });

                // Immediately proceed to Orchestrator with the now-local data
                onFineTune(modelHash, solverType, solver, femConfig);
            }
        } catch (err: any) {
            setSyncError(
                err.response?.data?.message ||
                    "Failed to sync remote weights before fine-tuning.",
            );
        } finally {
            setIsSyncing(false);
        }
    };

    return (
        <div className="bg-white border-t border-slate-100 transition-all">
            <div
                onClick={() => setIsExpanded(!isExpanded)}
                className={`p-4 pl-12 flex items-center justify-between cursor-pointer transition-colors select-none ${isExpanded ? "bg-slate-50/50" : "hover:bg-slate-50/30"}`}
            >
                <div className="flex items-center gap-4">
                    <div className="p-2 bg-indigo-50 rounded-lg border border-indigo-100 text-indigo-600 shrink-0">
                        <Brain size={18} />
                    </div>
                    <div className="min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-bold text-slate-800">
                                {solverType} Weights
                            </span>
                            {isShared && (
                                <span className="flex items-center gap-1 text-[10px] uppercase font-bold tracking-wider bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full border border-blue-100">
                                    <Cloud size={12} /> Cloud
                                </span>
                            )}
                            {isLocal && (
                                <span className="flex items-center gap-1 text-[10px] uppercase font-bold tracking-wider bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full border border-slate-200">
                                    <HardDrive size={12} /> Local
                                </span>
                            )}

                            <span className="font-mono bg-slate-100 text-slate-600 px-2 py-0.5 rounded text-[11px] font-semibold select-all">
                                {modelHash}
                            </span>
                        </div>
                        <p className="text-[11px] text-slate-500 mt-1 font-mono leading-relaxed wrap-break-words">
                            {compactConfigString}
                        </p>
                    </div>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                    <span className="text-xs font-bold px-2.5 py-1 bg-slate-100 text-slate-600 rounded-full border border-slate-200">
                        {linkedEvals.length}{" "}
                        {linkedEvals.length === 1 ? "Plot" : "Plots"}
                    </span>
                    {isExpanded ? (
                        <ChevronDown size={16} className="text-slate-400" />
                    ) : (
                        <ChevronRight size={16} className="text-slate-400" />
                    )}
                </div>
            </div>

            {isExpanded && (
                <div className="bg-slate-50/20 p-4 flex flex-col gap-3 animate-in slide-in-from-top-1 duration-150">
                    <ConfigGrid
                        title="Architecture & Training Configuration"
                        configObj={sanitizedSolver}
                    />

                    {/* ACTIONS ROW */}
                    <div className="flex justify-end items-start gap-2 my-1">
                        {/* Standard Sync Button */}
                        {isShared && !isLocal && serverIsConnected && (
                            <SyncWorkspaceButton
                                isLocal={isLocal}
                                syncPayload={syncPayload}
                                buttonLabel="Sync Model Weights"
                            />
                        )}

                        {/* Fine Tune / Sync Button Container */}
                        {serverIsConnected && (
                            <div className="flex flex-col items-end gap-1">
                                <button
                                    onClick={handleFineTuneAction}
                                    disabled={isSyncing}
                                    className="flex items-center gap-2 px-3 py-2 text-sm font-semibold text-indigo-700 bg-indigo-50 border border-indigo-200 hover:bg-indigo-100 rounded-lg shadow-sm transition-all disabled:opacity-70 disabled:cursor-not-allowed"
                                    title={
                                        isLocal
                                            ? "Load this configuration for fine-tuning or cloning"
                                            : "Sync data to local workspace and load configuration"
                                    }
                                >
                                    {isSyncing ? (
                                        <Loader2
                                            size={16}
                                            className="animate-spin"
                                        />
                                    ) : isLocal ? (
                                        <GitFork size={16} />
                                    ) : (
                                        <DownloadCloud size={16} />
                                    )}

                                    {isSyncing
                                        ? "Syncing Weights..."
                                        : isLocal
                                          ? "Fine-Tune Weights"
                                          : "Sync & Fine-Tune"}
                                </button>

                                {/* Error Message Display */}
                                {syncError && (
                                    <div className="flex items-center gap-1 text-red-600 text-xs font-medium max-w-xs text-right mt-1">
                                        <AlertCircle
                                            size={14}
                                            className="shrink-0"
                                        />
                                        <span>{syncError}</span>
                                    </div>
                                )}
                            </div>
                        )}

                        {isLocal && (
                            <div className="pt-0">
                                {" "}
                                {/* Wrapper to align perfectly with the button row */}
                                <DeleteButton
                                    targetHash={modelHash}
                                    targetType="model"
                                    mode="local"
                                    buttonLabel="Delete Local Model"
                                />
                            </div>
                        )}
                    </div>

                    {linkedEvals.length === 0 ? (
                        <p className="text-[11px] font-medium text-slate-400 italic pl-8 py-1">
                            No zero-shot evaluations generated for this weights
                            configuration.
                        </p>
                    ) : (
                        linkedEvals.map(([evalHash, evalObj]) => (
                            <EvaluationNode
                                key={evalHash}
                                evalHash={evalHash}
                                evalObj={evalObj}
                                solverType={solverType}
                                serverIsConnected={serverIsConnected}
                                registry={registry}
                            />
                        ))
                    )}
                </div>
            )}
        </div>
    );
}
