using DrWatson
@quickactivate "experiments_NeuralOperators"

using JLD2
using Lux
using NeuralOperators
using Reactant
using Statistics
using CairoMakie
using AlgebraOfGraphics

# Load custom modules
include(srcdir("DataGeneration.jl"))
using .DataGeneration

include(srcdir("DeepONetArch.jl"))
using .DeepONetArch

include(srcdir("HashRegistry.jl"))
using .HashRegistry

"""
    predict_deeponet(model, f_input, x_input, ps, st)

Performs the forward pass of the DeepONet.
Must be wrapped in `@compile` to correctly execute on the XLA backend.
"""
function predict_deeponet(model, f_input, x_input, ps, st)
    pred, _ = model((f_input, x_input), ps, st)
    return pred
end

"""
    run_plot_deeponet(; model_hash::String, kwargs...)

Evaluates a trained DeepONet model on an unseen parameter (Zero-Shot execution),
benchmarks its inference time against the Gridap FEM solver, and generates
a comparative plot.

It queries the central `registry.json` to automatically retrieve the original
`data_hash` and architecture details associated with the given `model_hash`.

# Required Arguments
- `model_hash::String`: The 12-character SHA-256 hash of the trained model.

# Keyword Arguments
- `sigma_test::Float64=0.03`: The unseen standard deviation to evaluate the model on.
- `m_sensors::Int=100`: Number of sensors (must match the trained model).
- `p_latent::Int=64`: Latent space dimension (must match the trained model).
- `hidden::Int=64`: Hidden layer nodes (must match the trained model).

# Output
- Saves a comparative visualization to `plots/deeponet/eval_<eval_hash>.png`.
- Updates `data/registry.json` under the "evaluations" category.
- **Returns:** `eval_hash::String` confirming successful plot generation.
"""
function run_plot_deeponet(;
    model_hash::String,
    sigma_test::Float64=0.03,
    m_sensors::Int=100,
    p_latent::Int=64,
    hidden::Int=64
)

    # Check the cache for already trained model
    registry = HashRegistry.load_registry()
    if !haskey(registry["models"], model_hash)
        error("Model hash [$model_hash] not found in registry.")
    end
    model_config = registry["models"][model_hash]
    data_hash = model_config["data_hash"] # Extract the hash of the original data
    m_type = lowercase(model_config["model_type"])

    # Configuration and evaluation
    config = @strdict(model_hash, sigma_test)
    eval_hash = HashRegistry.config_hash(config)
    save_path = plotsdir(m_type, "eval_$(eval_hash).png")

    if HashRegistry.check_registry("evaluations", eval_hash) && isfile(save_path)
        println("Plot already exists for Hash: [$eval_hash]. Check $save_path")
        return eval_hash
    end

    println("--- Starting DeepONet Zero-Shot Evaluation (Eval Hash: $eval_hash) ---")
    println("Evaluating unseen parameter: σ = $sigma_test")

    # Load Model Weights
    weights_path = datadir("models", m_type, "model_$(model_hash).jld2")
    weights_data = load(weights_path)
    ps_trained = weights_data["ps"]
    st_trained = weights_data["st"]
    max_u = weights_data["max_u"]

    # Load FEM Data generated by GridapROMs
    data_path = datadir("sims", "data_$(data_hash).jld2")
    fem_data = load(data_path)
    fem_config = fem_data["config"]
    x_grid = fem_data["x_grid"]
    t_grid = fem_data["t_grid"]

    N_x = length(x_grid)
    N_t = length(t_grid)

    # Reconstruct Architecture & Sensors from centralized module
    deepONet, x_sensors = DeepONetArch.build_deeponet(
        m_sensors=m_sensors,
        p_latent=p_latent,
        hidden=hidden,
        L=fem_config["L"]
    )

    # Setup Devices
    cdev = cpu_device()
    xdev = reactant_device(; force=true)
    ps_dev = ps_trained |> xdev
    st_dev = st_trained |> xdev

    # Format Inputs for DeepONet
    f_test_cpu = zeros(Float32, m_sensors, 1)
    pi_f32 = Float32(π)
    u₀(x) = (1.0f0 / √(2.0f0 * pi_f32 * sigma_test)) * exp(-x^2 / (2.0f0 * sigma_test))
    f_test_cpu[:, 1] .= Float32.(u₀.(x_sensors))

    x_flat = repeat(x_grid, outer=N_t)
    t_flat = repeat(t_grid, inner=N_x)
    x_test_cpu = Float32.(vcat(x_flat', t_flat'))

    f_test_dev = f_test_cpu |> xdev
    x_test_dev = x_test_cpu |> xdev

    # Compile the prediction function for XLA
    println("Compiling inference graph for XLA...")
    compiled_predict = Reactant.with_config(; dot_general_precision=PrecisionConfig.HIGH) do
        @compile predict_deeponet(deepONet, f_test_dev, x_test_dev, ps_dev, st_dev)
    end

    println("\nWARMUP PHASE: Compiling Gridap and XLA (This will take a moment)")

    # Warmup FEM
    _ = DataGeneration.generate_fem_snapshots(
        [[sigma_test]];
        order=fem_config["order"],
        L=fem_config["L"],
        nx=fem_config["nx"],
        t0=fem_config["t0"],
        dt=fem_config["dt"],
        tf=fem_config["tf"],
        c=fem_config["c"],
        θ=fem_config["theta"]
    )

    # Warmup DeepONet
    _ = compiled_predict(deepONet, f_test_dev, x_test_dev, ps_dev, st_dev)

    println(">>> Warmup complete! <<<")

    println("\nBENCHMARK PHASE: Measuring pure execution time...")

    # Generate High-Fidelity data for the new sigma
    println("Generating High-Fidelity FEM solution for σ = $sigma_test...")
    t_fem = @elapsed begin
        hf_results = DataGeneration.generate_fem_snapshots(
            [[sigma_test]];
            order=fem_config["order"],
            L=fem_config["L"],
            nx=fem_config["nx"],
            t0=fem_config["t0"],
            dt=fem_config["dt"],
            tf=fem_config["tf"],
            c=fem_config["c"],
            θ=fem_config["theta"]
        )
    end

    snapshots_true = hf_results.snapshots[:, 1, :]

    # Execute XLA Inference
    println("Running Neural Operator inference...")
    t_nn = @elapsed begin
        u_pred_dev = compiled_predict(deepONet, f_test_dev, x_test_dev, ps_dev, st_dev)
        u_pred_cpu = u_pred_dev |> cdev
    end

    # Denormalize and reshape predictions
    u_pred_cpu .*= max_u
    u_pred_matrix = reshape(vec(u_pred_cpu), N_x, N_t)

    println("\n=== BENCHMARK RESULTS (σ = $sigma_test) ===")
    println("FEM Computation Time:  $(round(t_fem, digits=4)) seconds")
    println("DeepONet Inference:    $(round(t_nn, digits=4)) seconds")
    println("Speedup Factor:        $(round(t_fem / max(t_nn, 1e-6), digits=1))x")
    println("====================================\n")


    # Plotting with AlgebraOfGraphics
    println("Preparing the plot...")
    AoG = AlgebraOfGraphics
    AoG.set_aog_theme!()

    t_indices = [1, div(N_t, 2), N_t]
    results, abs_errors, x_vals, x_vals2 = Float32[], Float32[], Float32[], Float32[]
    labels, alphas, alphas2 = String[], String[], String[]

    for idx in t_indices
        t_val = t_grid[idx]
        u_true = Float32.(snapshots_true[:, idx])
        u_pred = u_pred_matrix[:, idx]

        l2_error = sqrt(mean(abs2, u_pred .- u_true))
        rel_error = (l2_error / max(sqrt(mean(abs2, u_true)), 1e-8)) * 100
        text_label = "t = $(round(t_val, digits=2))\n(Err: $(round(rel_error, digits=2))%)"

        append!(results, u_true)
        append!(labels, repeat(["High-Fidelity"], N_x))

        append!(results, u_pred)
        append!(labels, repeat(["DeepONet"], N_x))

        append!(x_vals, repeat(Float32.(x_grid), 2))
        append!(alphas, repeat([text_label], N_x * 2))

        append!(abs_errors, abs.(u_pred .- u_true))
        append!(x_vals2, Float32.(x_grid))
        append!(alphas2, repeat([text_label], N_x))
    end

    plot_data = (; results, abs_errors, x_vals, alphas, labels, x_vals2, alphas2)

    fig = Figure(; size=(1024, 512), title="DeepONet vs HF (σ = $sigma_test)")
    axis_common = (; xlabelsize=16, ylabelsize=16, titlesize=16)

    axs1 = draw!(
        fig[1, 1],
        AoG.data(plot_data) *
        mapping(:x_vals => L"x", :results => L"u(x, t)"; color=:labels => "", col=:alphas => "", linestyle=:labels => "") *
        visual(Lines; linewidth=3),
        scales(; Color=(; palette=[:orange, :blue]), LineStyle=(; palette=[:solid, :dash]));
        axis=merge(axis_common, (; xlabel=""))
    )
    for ax in axs1
        hidexdecorations!(ax; grid=false)
    end
    axislegend(axs1[1, 1].axis, [LineElement(; linestyle=:solid, color=:orange), LineElement(; linestyle=:dash, color=:blue)], ["High-Fidelity", "DeepONet"], position=:lt)

    axs2 = draw!(
        fig[2, 1],
        AoG.data(plot_data) * mapping(:x_vals2 => L"x", :abs_errors => L"|u_{pred} - u_{true}|"; col=:alphas2 => "") * visual(Lines; linewidth=3, color=:green);
        axis=merge(axis_common, (; titlevisible=false))
    )

    mkpath(plotsdir(m_type))
    save(save_path, fig)
    HashRegistry.update_registry!("evaluations", eval_hash, config)

    println("Evaluation successful! Plot saved to: $save_path")

    return eval_hash
end

# Executed only when run from bash terminal
if abspath(PROGRAM_FILE) == @__FILE__
    # Allow passing structural parameters if testing different architectures
    s_test = length(ARGS) > 0 ? parse(Float32, ARGS[1]) : 0.03
    m_sens = length(ARGS) > 1 ? parse(Int, ARGS[2]) : 100
    p_lat = length(ARGS) > 2 ? parse(Int, ARGS[3]) : 64
    hid = length(ARGS) > 3 ? parse(Int, ARGS[4]) : 64

    run_plot_deeponet(
        sigma_test=s_test,
        m_sensors=m_sens,
        p_latent=p_lat,
        hidden=hid
    )
end
