using DrWatson
@quickactivate "experiments_NeuralOperators"

using JLD2
using Lux
using NeuralOperators
using Optimisers
using Reactant
using Enzyme
using Random
using Statistics
using MLUtils
# using CairoMakie, AlgebraOfGraphics

# Load data generation module
include(srcdir("DeepONetArch.jl"))
using .DeepONetArch

"""
    train_deeponet!(train_state, data; epochs=5000)

Executes the training loop for the DeepONet model.
The function expects an already initialized `TrainState`.
Note: The first epoch will trigger the XLA and Enzyme JIT compilation,
which usually takes a few minutes. After that epochs will be extremely fast.

# Arguments
- `train_state`: already initialized `TrainState`.
- `data`: A tuple containing the formatted training data `((f_data, x_data), u_data)`.

# Keyword Arguments
- `epochs::Int=5000`: Number of training epochs. Default is set low for fast demonstration.

# Returns
- `ps`: Trained model parameters.
- `st`: Updated model states.
"""
function train_deeponet!(train_state, data; epochs=5000)
    println("--- Starting Training on Reactant Device ---")
    println("(The first epoch will trigger XLA/Enzyme compilation and may take 2-4 minutes)")

    t_start = time()
    lr_stage = 1

    Reactant.with_config(; dot_general_precision=PrecisionConfig.HIGH) do
        for epoch in 1:epochs
            _, loss, _, train_state = Training.single_train_step!(
                AutoEnzyme(), MSELoss(), data, train_state; return_gradients=Val(false)
            )

            current_loss = Float32(loss)

            if current_loss < 1e-4 && lr_stage == 1
                println(">>> Epoch $epoch: Loss < 1e-4. Cutting LR to 0.0005 <<<")
                Optimisers.adjust!(train_state.optimizer_state, 0.0005f0)
                lr_stage = 2
            elseif current_loss < 5e-5 && lr_stage == 2
                println(">>> Epoch $epoch: Loss < 5e-5. Cutting LR to 0.0001 <<<")
                Optimisers.adjust!(train_state.optimizer_state, 0.0001f0)
                lr_stage = 3
            elseif current_loss < 2.3e-5 && lr_stage == 3
                println(">>> Epoch $epoch: Loss < 2.3e-5. Cutting LR to 0.00001 <<<")
                Optimisers.adjust!(train_state.optimizer_state, 0.00001f0)
                lr_stage = 4
            end

            if epoch == 1
                t_compiled = time()
                comp_time = round((t_compiled - t_start) / 60, digits=2)
                println(">>> Compilation and 1st Epoch finished in $comp_time minutes. Starting fast training... <<<")
                println("Epoch: $epoch \t Loss: $(Float32(loss))")

            elseif epoch % 500 == 0
                println("Epoch: $epoch \t Loss: $(Float32(loss))")
            end
        end
    end

    t_end = time()
    total_mins = round((t_end - t_start) / 60, digits=2)
    println("--- Training Completed in $total_mins minutes ---")

    return train_state.parameters, train_state.states
end

"""
    run_train_deeponet(; kwargs...)

Loads the High-Fidelity FEM snapshots, formats them into Branch (sensors) and
Trunk (coordinates) inputs, and orchestrates the DeepONet training loop via XLA.

# Keyword Arguments
- `n_epochs::Int=20000`: Total training epochs.
- `step_x::Int=10`: Spatial subsampling step (reduces grid size).
- `step_t::Int=5`: Temporal subsampling step.
- `m_sensors::Int=100`: Number of input sensors for the Branch Net.
- `p_latent::Int=64`: Dimensionality of the latent space (output of Branch/Trunk).
- `hidden::Int=64`: Number of neurons per hidden layer in the MLPs.

# Output
Saves the trained model weights and normalization factors to `data/models/deeponet_weights.jld2`.
"""
function run_train_deeponet(;
    n_epochs::Int=20000,
    step_x::Int=10,
    step_t::Int=5,
    m_sensors::Int=100,
    p_latent::Int=64,
    hidden::Int=64,
)
    println("--- Starting DeepONet ---")

    # Load FEM Data generated by GridapROMs
    data_path = datadir("sims", "fem_snapshots.jld2")
    if !isfile(data_path)
        error("Data file not found. Run generate_data.jl first.")
    end

    fem_data = load(data_path)              # Returns a dict
    snapshots = fem_data["snapshots"]       # Shape: (N_dofs, N_sigma, N_time)
    x_grid = fem_data["x_grid"]             # Spatial DoFs
    t_grid = fem_data["t_grid"]             # Time steps
    σ_values = fem_data["sigma_values"]     # Sigma parameters
    config = fem_data["config"]             # Extract config to get physical domain L

    N_x_full, N_sigma, N_t_full = size(snapshots)
    println("Loaded FEM Snapshots: $N_x_full spatial DoFs, $N_t_full time steps, $N_sigma parameters.")

    # Data Formatting for DeepONet
    idx_x = 1:step_x:N_x_full
    idx_t = 1:step_t:N_t_full

    x_red = x_grid[idx_x]
    t_red = t_grid[idx_t]
    N_x_red = length(x_red)
    N_t_red = length(t_red)
    N_points = N_x_red * N_t_red

    println("Reduced grid for fast training: $N_points points per parameter.")

    # Model Definition (DeepONet)
    deepONet, x_sensors = DeepONetArch.build_deeponet(
        m_sensors=m_sensors,
        p_latent=p_latent,
        hidden=hidden,
        L=config["L"]
    )

    # Branch Net Input (Sensors): f_train
    # We sample the initial condition u0 at fixed sensor locations
    f_train = zeros(Float32, m_sensors, N_sigma)

    pi_f32 = Float32(π)
    for (i, σ_val) in enumerate(σ_values)
        σ = σ_val[1]
        u₀(x) = (1 / √(2 * pi_f32 * σ)) * exp(-x^2 / (2 * σ))
        f_train[:, i] .= Float32.(u₀.(x_sensors))
    end

    # Trunk Net Input (Spatio-temporal coordinates): x_train
    # Create a flattened meshgrid of (x, t)
    x_flat = repeat(x_red, outer=N_t_red)
    t_flat = repeat(t_red, inner=N_x_red)
    x_train = Float32.(vcat(x_flat', t_flat')) # Shape: (2, N_points)

    # Target Output: u_train
    u_train = zeros(Float32, N_points, N_sigma)
    snapshots_red = @views snapshots[idx_x, :, idx_t]

    for i in 1:N_sigma
        u_train[:, i] .= Float32.(vec(snapshots_red[:, i, :]))
    end

    # Normalize targets for stable training
    max_u = maximum(abs.(u_train))
    u_train ./= max_u

    println("\n=== DeepONet Tensor Shapes ===")
    println("Original Grid         : $(N_x_full) space * $(N_t_full) time")
    println("Reduced Grid        : $(N_x_red) space * $(N_t_red) time = $(N_points) points")
    println("Branch Input (f_train): $(size(f_train)) \t -->\t (m_sensors, N_sigma)")
    println("Trunk Input  (x_train): $(size(x_train)) \t -->\t (2_coordinates, N_points)")
    println("Target Output (u_train): $(size(u_train)) \t-->\t (N_points, N_sigma)")
    println("==============================\n")


    # Device Setup and XLA Compilation (Reactant.jl)
    xdev = reactant_device(; force=true)
    cdev = cpu_device()

    rng = Random.default_rng()
    Random.seed!(rng, 42)
    ps, st = Lux.setup(rng, deepONet) |> xdev

    # Move data to XLA device
    f_data = f_train |> xdev
    x_data = x_train |> xdev
    u_data = u_train |> xdev
    train_data = ((f_data, x_data), u_data)

    # Training Loop
    println("\n--- Initializing Optimizer and TrainState ---")
    opt = Adam(0.001f0)
    train_state = Training.TrainState(deepONet, ps, st, opt)

    # We use @time to show exactly how long the compilation + execution took
    @time ps_trained, st_trained = train_deeponet!(
        train_state, train_data;
        epochs=n_epochs
    )

    # Save Model Weights
    models_dir = datadir("models")
    mkpath(models_dir)
    weights_path = joinpath(models_dir, "deeponet_weights.jld2")

    # Move parameters back to CPU before saving
    ps_cpu = ps_trained |> cdev
    st_cpu = st_trained |> cdev
    jldsave(weights_path; ps=ps_cpu, st=st_cpu, max_u=max_u)

    println("Model weights saved to $weights_path")
    println("DeepONet integration script finished successfully")
end

# Executed only when run from bash terminal
if abspath(PROGRAM_FILE) == @__FILE__
    # Allow terminal execution with: julia train_deeponet.jl [epochs] [step_x] [step_t]
    e_val = length(ARGS) > 0 ? parse(Int, ARGS[1]) : 20000
    sx_val = length(ARGS) > 1 ? parse(Int, ARGS[2]) : 10
    st_val = length(ARGS) > 2 ? parse(Int, ARGS[3]) : 5

    run_train_deeponet(n_epochs=e_val, step_x=sx_val, step_t=st_val)
end
