module Pipelines

using DrWatson, JLD2, AlgebraOfGraphics, CairoMakie, Gridap

# Custom modules
using ..TrainingLoops, ..ModelTypes, ..DataGeneration, ..HashRegistry, ..Inference, ..Utils

export execute_train_pipeline, execute_plot_pipeline

"""
    execute_train_pipeline(model::AbstractNeuralModel, config::Dict)

Internal core function. Handles cache validation, loading the High-Fidelity dataset,
triggering the specialized training dispatch (via `prepare_and_train`), and saving
the resulting weights to disk.

# Arguments
- `model`: An instance of a concrete neural model type (e.g., `DeepONet()`).
- `config::Dict`: A complete dictionary containing all hyperparameters, including defaults,
  to guarantee deterministic and collision-free SHA-256 hashing.

# Returns
- `model_hash::String`: The unique hash identifier of the trained model.
"""
function execute_train_pipeline(model::ModelTypes.AbstractNeuralModel, config::Dict)
    model_type = config["model_type"]
    data_hash = config["data_hash"]

    # Generate deterministic hash from the fully populated config
    model_hash = HashRegistry.config_hash(config)
    weights_path = datadir("models", lowercase(model_type), "model_$(model_hash).jld2")

    # Cache check
    if HashRegistry.check_registry("models", model_hash) && isfile(weights_path)
        println("Model already trained with Hash: [$model_hash]. Skipping training.")
        return model_hash
    end

    # Load FEM Data generated by GridapROMs
    println("--- Training New Model (Hash: $model_hash) on Data ($data_hash) ---")
    data_path = datadir("sims", "data_$(data_hash).jld2")
    if !isfile(data_path)
        error("Required data hash [$data_hash] not found! Run generation first.")
    end

    fem_data = load(data_path)

    # Delegate to specialized Dispatch
    ps_cpu, st_cpu, max_u = prepare_and_train(model, fem_data, config)

    # Save Model Weights and Update Registry
    mkpath(datadir("models", lowercase(model_type)))
    jldsave(weights_path; ps=ps_cpu, st=st_cpu, max_u=max_u)
    HashRegistry.update_registry!("models", model_hash, config)

    println("Model weights saved to $weights_path")
    println("$(model_type) integration script finished successfully")

    return model_hash
end

"""
    execute_plot_pipeline(model::AbstractNeuralModel, config::Dict)

Internal core function. Handles registry validation, executing the High-Fidelity
FEM solver for benchmarking, triggering the model-specific inference dispatch,
and generating the comparative AlgebraOfGraphics plots.

# Arguments
- `model`: An instance of a concrete neural model type (e.g., `DeepONet()`).
- `config::Dict`: A dictionary containing `model_hash` and `sigma_test`.

# Returns
- `eval_hash::String`: The unique hash identifier of the evaluation.
"""
function execute_plot_pipeline(model::ModelTypes.AbstractNeuralModel, config::AbstractDict)
    model_hash = config["model_hash"]
    sigma_test = config["sigma_test"]
    model_type = ModelTypes.get_model_name(model)

    # Cache check
    eval_hash = HashRegistry.config_hash(config)
    save_path = plotsdir(lowercase(model_type), "eval_$(eval_hash).png")

    if HashRegistry.check_registry("evaluations", eval_hash) && isfile(save_path)
        println("Plot already exists for Hash: [$eval_hash]. Check $save_path")
        return eval_hash
    end

    # Extract Registry and Metadata
    registry = HashRegistry.load_registry()
    if !haskey(registry["models"], model_hash)
        error("Model hash [$model_hash] not found in registry.")
    end

    model_config = registry["models"][model_hash]
    data_hash = model_config["data_hash"]

    println("--- Starting $model_type Zero-Shot Evaluation (Eval Hash: $eval_hash) ---")
    println("Evaluating unseen parameter: σ = $sigma_test")

    # Load Dependencies
    weights_path = datadir("models", lowercase(model_type), "model_$(model_hash).jld2")
    weights_data = load(weights_path)

    data_path = datadir("sims", "data_$(data_hash).jld2")
    fem_data = load(data_path)
    fem_config = fem_data["config"]

    # Execute High-Fidelity FEM
    println("\nWARMUP PHASE: Compiling Gridap (This will take a moment)")
    _ = DataGeneration.generate_fem_snapshots(
        [[sigma_test]];
        order=fem_config["order"], L=fem_config["L"], nx=fem_config["nx"],
        t0=fem_config["t0"], dt=fem_config["dt"], tf=fem_config["tf"],
        c=fem_config["c"], θ=fem_config["theta"]
    )

    println("\nBENCHMARK PHASE: Measuring pure FEM execution time...")
    println("Generating High-Fidelity FEM solution for σ = $sigma_test...")
    t_fem = @elapsed begin
        hf_results = DataGeneration.generate_fem_snapshots(
            [[sigma_test]];
            order=fem_config["order"], L=fem_config["L"], nx=fem_config["nx"],
            t0=fem_config["t0"], dt=fem_config["dt"], tf=fem_config["tf"],
            c=fem_config["c"], θ=fem_config["theta"]
        )
    end
    x_hf_raw = hf_results.snapshots[:, 1, :]

    # Specialized Neural Inference Dispatch
    u_pred_matrix, t_grid_pred, t_nn = evaluate_and_predict(
        model, weights_data, fem_data, model_config, sigma_test
    )

    println("\n=== BENCHMARK RESULTS (σ = $sigma_test) ===")
    println("FEM Computation Time:  $(round(t_fem, digits=4)) seconds")
    println("$model_type Inference:    $(round(t_nn, digits=4)) seconds")
    println("Speedup Factor:        $(round(t_fem / max(t_nn, 1e-6), digits=1))x")
    println("====================================\n")

    # Plotting Generation
    println("Preparing the plot...")
    AoG = AlgebraOfGraphics
    AoG.set_aog_theme!()

    N_x_full = length(fem_data["x_grid"])
    N_t_plot = length(t_grid_pred)

    # Select start, middle, and end frames of the network's prediction
    t_indices = [1, div(N_t_plot, 2), N_t_plot]
    results, abs_errors, x_vals, x_vals2 = Float32[], Float32[], Float32[], Float32[]
    labels, alphas, alphas2 = String[], String[], String[]

    for idx in t_indices
        t_val = t_grid_pred[idx]

        # Robust mapping: Find the closest true HF timeframe regardless of ML subsampling
        idx_true = argmin(abs.(fem_data["t_grid"] .- t_val))
        u_true = Float32.(x_hf_raw[:, idx_true])

        u_pred = vec(u_pred_matrix[:, idx])

        l2_error = sqrt(mean(abs2, u_pred .- u_true))
        rel_error = (l2_error / max(sqrt(mean(abs2, u_true)), 1e-8)) * 100
        text_label = "t = $(round(t_val, digits=2))\n(Err: $(round(rel_error, digits=2))%)"

        append!(results, u_true)
        append!(labels, repeat(["High-Fidelity"], N_x_full))

        append!(results, u_pred)
        append!(labels, repeat([model_type], N_x_full))

        append!(x_vals, repeat(Float32.(fem_data["x_grid"]), 2))
        append!(alphas, repeat([text_label], N_x_full * 2))

        append!(abs_errors, abs.(u_pred .- u_true))
        append!(x_vals2, Float32.(fem_data["x_grid"]))
        append!(alphas2, repeat([text_label], N_x_full))
    end

    plot_data = (; results, abs_errors, x_vals, alphas, labels, x_vals2, alphas2)

    fig = Figure(; size=(1024, 512), title="$model_type vs HF (σ = $sigma_test)", titlesize=25)
    axis_common = (; xlabelsize=20, ylabelsize=20, titlesize=20, xticklabelsize=20, yticklabelsize=20)

    axs1 = draw!(
        fig[1, 1],
        AoG.data(plot_data) *
        mapping(:x_vals => L"x", :results => L"u(x, t)"; color=:labels => "", col=:alphas => "", linestyle=:labels => "") *
        visual(Lines; linewidth=4),
        scales(; Color=(; palette=[:orange, :blue]), LineStyle=(; palette=[:solid, :dash]));
        axis=merge(axis_common, (; xlabel=""))
    )
    for ax in axs1
        hidexdecorations!(ax; grid=false)
    end
    axislegend(axs1[1, 1].axis, [LineElement(; linestyle=:solid, color=:orange), LineElement(; linestyle=:dash, color=:blue)], ["High-Fidelity", model_type], position=:lt)

    axs2 = draw!(
        fig[2, 1],
        AoG.data(plot_data) * mapping(:x_vals2 => L"x", :abs_errors => L"|u_{pred} - u_{true}|"; col=:alphas2 => "") * visual(Lines; linewidth=4, color=:green);
        axis=merge(axis_common, (; titlevisible=false))
    )

    mkpath(plotsdir(lowercase(model_type)))
    save(save_path, fig)
    HashRegistry.update_registry!("evaluations", eval_hash, config)

    println("Evaluation successful! Plot saved to: $save_path")

    return eval_hash
end

end
