module Pipelines

using DrWatson, JLD2, AlgebraOfGraphics, CairoMakie, Gridap

# Custom modules
using ..TrainingLoops, ..Solvers, ..DataGeneration, ..HashRegistry, ..Inference, ..Utils, ..LRSchedulers

export execute_train_pipeline, execute_plot_pipeline

"""
    execute_train_pipeline(model::AbstractNeuralModel, config::Dict, lr_scheduler)

Internal core function. Handles cache validation, loading the High-Fidelity dataset,
triggering the specialized training dispatch (via `prepare_and_train`), and saving
the resulting weights to disk.

# Arguments
- `model`: An instance of a concrete neural model type (e.g., `DeepONet()`).
- `config::Dict`: A complete dictionary containing all hyperparameters, including defaults,
  to guarantee deterministic and collision-free SHA-256 hashing.
- `lr_scheduler`: The concrete learning rate scheduler instance to be used during training.

# Returns
- `model_hash::String`: The unique hash identifier of the trained model.
"""
function execute_train_pipeline(solver::AbstractNeuralSolver, data_hash::String)
    solver_name = get_solver_name(solver)

    # Dict for deterministic hash
    config_dict = Dict(
        "solver_type" => solver_name,
        "solver" => HashRegistry.struct_to_dict(solver),
        "data_hash" => data_hash
    )
    model_hash = HashRegistry.config_hash(config_dict)
    weights_path = datadir("models", lowercase(solver_name), "model_$(model_hash).jld2")

    # Cache check
    if HashRegistry.check_registry("models", model_hash) && isfile(weights_path)
        println("Model already trained with Hash: [$model_hash]. Skipping training.")
        return model_hash
    end

    # Load FEM Data generated by GridapROMs
    println("--- Training New Model (Hash: $model_hash) on Data ($data_hash) ---")
    data_path = datadir("sims", "data_$(data_hash).jld2")
    if !isfile(data_path)
        error("Required data hash [$data_hash] not found! Run generation first.")
    end

    fem_data = load(data_path)

    # Get the scheduler from the struct
    lr_scheduler = init_scheduler(solver.lr_scheduler, solver.epochs)

    # Delegate to specialized Dispatch
    ps_cpu, st_cpu, max_u = prepare_and_train(solver, fem_data, lr_scheduler)

    # Save Model Weights and Update Registry
    mkpath(datadir("models", lowercase(solver_name)))
    jldsave(weights_path; ps=ps_cpu, st=st_cpu, max_u=max_u)
    HashRegistry.update_registry!("models", model_hash, config_dict)

    println("Model weights saved to $weights_path")
    println("$(solver_name) integration script finished successfully")

    return model_hash
end

"""
    execute_plot_pipeline(model::AbstractNeuralModel, config::Dict)

Internal core function. Handles registry validation, executing the High-Fidelity
FEM solver for benchmarking, triggering the model-specific inference dispatch,
and generating the comparative AlgebraOfGraphics plots.

# Arguments
- `model`: An instance of a concrete neural model type (e.g., `DeepONet()`).
- `config::Dict`: A dictionary containing `model_hash` and `sigma_test`.

# Returns
- `eval_hash::String`: The unique hash identifier of the evaluation.
"""
function execute_plot_pipeline(solver::AbstractNeuralSolver, model_hash::String, eval_config::EvalConfig)
    solver_name = get_solver_name(solver)
    sigma_test = eval_config.sigma_test

    config_dict = Dict(
        "model_hash" => model_hash,
        "eval_config" => HashRegistry.struct_to_dict(eval_config)
    )

    # Cache check
    eval_hash = HashRegistry.config_hash(config_dict)
    save_path = plotsdir(lowercase(solver_name), "eval_$(eval_hash).png")

    if HashRegistry.check_registry("evaluations", eval_hash) && isfile(save_path)
        println("Plot already exists for Hash: [$eval_hash]. Check $save_path")
        return eval_hash
    end

    # Extract Registry and Metadata
    registry = HashRegistry.load_registry()
    if !haskey(registry["models"], model_hash)
        error("Model hash [$model_hash] not found in registry.")
    end

    model_config = registry["models"][model_hash]
    data_hash = model_config["data_hash"]

    println("--- Starting $solver_name Zero-Shot Evaluation (Eval Hash: $eval_hash) ---")
    println("Evaluating unseen parameter: σ = $sigma_test")

    # Load Dependencies
    weights_path = datadir("models", lowercase(solver_name), "model_$(model_hash).jld2")
    weights_data = load(weights_path)

    data_path = datadir("sims", "data_$(data_hash).jld2")
    fem_data = load(data_path)

    # Build the FEMConfig from the dataset dictionary
    fem_config = FEMConfig(; (Symbol(k) => v for (k, v) in fem_data["config"])...)

    # Execute High-Fidelity FEM
    println("\nWARMUP PHASE: Compiling Gridap (This will take a moment)")
    _ = DataGeneration.generate_fem_snapshots([[sigma_test]], fem_config)

    println("\nBENCHMARK PHASE: Measuring pure FEM execution time...")
    println("Generating High-Fidelity FEM solution for σ = $sigma_test...")
    t_fem = @elapsed begin
        hf_results = DataGeneration.generate_fem_snapshots([[sigma_test]], fem_config)
    end
    x_hf_raw = hf_results.snapshots[:, 1, :]

    # Specialized Neural Inference Dispatch
    u_pred_matrix, t_grid_pred, t_nn = evaluate_and_predict(
        solver, weights_data, fem_data, sigma_test
    )

    println("\n=== BENCHMARK RESULTS (σ = $sigma_test) ===")
    println("FEM Computation Time:  $(round(t_fem, digits=4)) seconds")
    println("$solver_name Inference:    $(round(t_nn, digits=4)) seconds")
    println("Speedup Factor:        $(round(t_fem / max(t_nn, 1e-6), digits=1))x")
    println("====================================\n")

    # Plotting Generation
    println("Preparing the plot...")

    N_t_plot = length(t_grid_pred)
    t_indices = [1, div(N_t_plot, 2), N_t_plot]

    # figure generation
    fig = Figure(; size=(1200, 800))

    # Title creation
    speedup = round(t_fem / max(t_nn, 1e-6), digits=1)
    fig_title = "$solver_name vs High-Fidelity FEM (Zero-Shot) | σ = $sigma_test | Grid: $(length(fem_data["x_grid"])) × $(N_t_plot) | Speedup: $(speedup)x"
    Label(fig[0, 1:3], fig_title, fontsize=24, font=:bold)

    # Lists for the axis
    axs_top = Axis[]
    axs_bot = Axis[]

    for (i, idx) in enumerate(t_indices)
        t_val = t_grid_pred[idx]

        # mapping to find the closest HF frame
        idx_true = argmin(abs.(fem_data["t_grid"] .- t_val))
        u_true = Float32.(x_hf_raw[:, idx_true])
        u_pred = vec(u_pred_matrix[:, idx])

        # Errors
        abs_err = abs.(u_pred .- u_true)
        l2_error = sqrt(mean(abs2, u_pred .- u_true))
        rel_error = (l2_error / max(sqrt(mean(abs2, u_true)), 1e-8)) * 100

        text_label = "t = $(round(t_val, digits=2))\n(Err: $(round(rel_error, digits=2))%)"

        # first row (u_true vs u_pred)
        ax_top = Axis(fig[1, i],
            title=text_label, titlesize=18,
            ylabel=i == 1 ? L"u(x, t)" : "",
            ylabelsize=22, xticklabelsize=16, yticklabelsize=16
        )
        push!(axs_top, ax_top)

        lines!(ax_top, fem_data["x_grid"], u_true, label="High-Fidelity", color=:orange, linewidth=4)
        lines!(ax_top, fem_data["x_grid"], u_pred, label=solver_name, color=:blue, linestyle=:dash, linewidth=4)

        if i > 1
            hideydecorations!(ax_top, grid=false)
        end

        # Second row (error)
        ax_bot = Axis(fig[2, i],
            xlabel=L"x",
            ylabel=i == 1 ? L"|u_{\text{pred}} - u_{\text{HF}}|" : "",
            xlabelsize=22, ylabelsize=22, xticklabelsize=16, yticklabelsize=16
        )
        push!(axs_bot, ax_bot)

        lines!(ax_bot, fem_data["x_grid"], abs_err, color=:green, linewidth=4)

        if i > 1
            hideydecorations!(ax_bot, grid=false)
        end
    end

    # Axes syncronization
    linkyaxes!(axs_top...)
    linkyaxes!(axs_bot...)
    linkxaxes!(axs_top..., axs_bot...)

    #= Hide x axe on the first row
    for ax in axs_top
        hidexdecorations!(ax, grid=false)
    end=#

    # Add legends
    axislegend(axs_top[1], position=:lt, labelsize=18)

    # Layout and spaces
    rowgap!(fig.layout, 1, 15) # Space under the title
    rowgap!(fig.layout, 2, 10)
    colgap!(fig.layout, 15)

    # Storing
    mkpath(plotsdir(lowercase(solver_name)))
    save(save_path, fig)
    HashRegistry.update_registry!("evaluations", eval_hash, config_dict)

    println("Evaluation successful! Plot saved to: $save_path")

    return eval_hash
end

end
